In [1]:
import pandas as pd
import numpy as np

In [3]:
reflat = pd.read_csv('/home/groups/horence/refFlat_GRCh38',sep='\t')
reflat.head()

,#hg38.knownGene.name,hg38.kgXref.geneSymbol,hg38.kgXref.refseq,hg38.kgXref.description
0,ENST00000456328.2,DDX11L1,NR_148357,Homo sapiens DEAD/H-box helicase 11 pseudogene...
1,ENST00000450305.2,DDX11L1,NaN,DEAD/H-box helicase 11 like 1 (from HGNC DDX11L1)
2,ENST00000488147.1,WASH7P,NR_024540,"Homo sapiens WASP family homolog 7, pseudogene..."
3,ENST00000619216.1,MIR6859-1,NR_106918,"Homo sapiens microRNA 6859-1 (MIR6859-1), micr..."
4,ENST00000473358.1,MIR1302-2HG,NaN,MIR1302-2 host gene (from HGNC MIR1302-2HG)

In [4]:
spots = pd.read_csv('../processed_data/all_passing_rna_spots.csv')
spots.head()

,global_x,global_y,global_z,target_molecule_name,num_assigned_cells,cell_id,sample
0,-4237.7397,1681.8490,0.0,Acta2,1,217951229059897556843731256135790480948,mouse1sample2
1,-4183.0010,1688.5905,0.0,Acta2,1,281878279612082858224382179441472205807,mouse1sample2
2,-4215.4233,1699.2443,0.0,Acta2,1,271699149458331512543397347819513343392,mouse1sample2
3,-4207.3945,1706.8620,0.0,Acta2,1,271699149458331512543397347819513343392,mouse1sample2
4,-4206.7200,1711.7010,0.0,Acta2,1,271699149458331512543397347819513343392,mouse1sample2

In [6]:
genes = spots['target_molecule_name'].unique()
genes

array(['Acta2', 'Adam2', 'Ankfn1', 'Ano4', 'Aqp4', 'Asic4', 'B4galnt3',
       'Barx2', 'Bcl11b', 'Bdnf', 'Blnk', 'Bmpr1b', 'C1ql3', 'Cacng5',
       'Calb2', 'Camk2d', 'Car3', 'Cbln2', 'Cbln4', 'Ccbe1', 'Ccdc3',
       'Cd14', 'Cd24a', 'Cdcp1', 'Cdh12', 'Cdh13', 'Cdh20', 'Cdh9',
       'Ceacam9', 'Cemip', 'Chn2', 'Chrm2', 'Cldn5', 'Cntnap5b', 'Cobll1',
       'Col15a1', 'Col23a1', 'Col24a1', 'Col25a1', 'Cplx3', 'Crispld2',
       'Cspg4', 'Ctss', 'Cux2', 'Cxcl14', 'Daam2', 'Dnase1l3', 'Dscaml1',
       'Egfem1', 'Egfr', 'Elfn1', 'Epha7', 'Fam19a2', 'Fam84b', 'Fbxl7',
       'Fezf2', 'Flrt3', 'Flt1', 'Fosb', 'Frem2', 'Fst', 'Gfap', 'Gpc6',
       'Grik1', 'Grin3a', 'Grm1', 'Grm8', 'Hs3st5', 'Igf2', 'Igfbp5',
       'Ikzf2', 'Inpp4b', 'Iqgap2', 'Itgb8', 'Kcng1', 'L3mbtl4', 'Lama3',
       'Lhx6', 'Lmo1', 'Lsp1', 'Luzp2', 'Lypd1', 'March1', 'Marcksl1',
       'Meis2', 'Mrc1', 'Myh14', 'Ndst4', 'Nkain3', 'Nnmt', 'Nos1',
       'Npnt', 'Nr2f2', 'Nr4a1', 'Nr4a2', 'Ntng2', 'Nxph1', 'Nxph4',
       'Olah', 'Olfm3', 'Oprk1', 'Osr1', 'Otof', 'Parm1', 'Pcdh8',
       'Pde11a', 'Pdgfc', 'Pdgfra', 'Pdlim5', 'Phactr2', 'Plch1',
       'Plcxd3', 'Pld5', 'Plekhg3', 'Pou3f1', 'Pou3f3', 'Pou6f2', 'Prdm8',
       'Prox1', 'Prr16', 'Prss12', 'Ptger3', 'Ptprk', 'Ptprm', 'Ptprt',
       'Ptpru', 'Pxdc1', 'Ramp1', 'Reln', 'Rfx3', 'Rgs5', 'Rgs6',
       'Rnf152', 'Ror1', 'Rorb', 'Rxfp1', 'Rxfp2', 'Satb2', 'Scgn',
       'Sema5a', 'Sertm1', 'Sgcd', 'Shisa9', 'Slc17a6', 'Slc17a8',
       'Slc25a13', 'Slc30a3', 'Slc32a1', 'Slc44a5', 'Slco5a1', 'Sox10',
       'Sox6', 'Spon1', 'St6galnac5', 'Sulf1', 'Sulf2', 'Syndig1',
       'Syt10', 'Syt6', 'Tbc1d4', 'Tcap', 'Tenm3', 'Thbs2', 'Thsd7a',
       'Timp3', 'Tmem163', 'Tmtc2', 'Tox', 'Trp53i11', 'Trpc4', 'Trpc6',
       'Tshz2', 'Tunar', 'Ubash3b', 'Unc13c', 'Unc5b', 'Unc5d', 'Ust',
       'Vipr2', 'Vtn', 'Vwc2', 'Wipf3', 'Wnt7b', 'Zfp804b', 'Blank-2',
       'Blank-4', '1810046K07Rik', 'Adamts2', 'Adamts4', 'Adra1b', 'Alk',
       'Bgn', 'Brinp3', 'Ccdc162', 'Cdca7', 'Chat', 'Chrna2', 'Col14a1',
       'Corin', 'Crhr2', 'Egln3', 'Egr2', 'Enpp6', 'Foxp2', 'Glra1',
       'Igfbp4', 'Il4ra', 'Kcnj8', 'Ltf', 'Moxd1', 'Mrgprx2', 'Nhs',
       'Npsr1', 'Prss23', 'Rspo1', 'Sema3e', 'Sncg', 'Tnfaip6', 'Blank-6',
       'Blank-10', '5730522E02Rik', 'Ccdc80', 'Dmkn', 'Hpse', 'Il1rapl2',
       'Lyzl4', 'Muc20', 'Npas1', 'Th', 'Blank-3', 'Blank-8', 'Blank-9',
       'Chodl', 'Clrn1', 'Nxph2', 'Prokr2', 'Rerg', 'Blank-1', 'Blank-7',
       'B4galnt2', 'Ccnb1', 'Npy2r', 'Prok2', 'Serpinf1', 'Sp8', 'Teddm3',
       'C1qtnf7', '1700022I11Rik', 'Fndc7', 'Opalin', '5031425F14Rik',
       'Blank-5'], dtype=object)

In [7]:
len(genes)

252

In [10]:
genes = [g.upper() for g in genes]
genes

['ACTA2',
 'ADAM2',
 'ANKFN1',
 'ANO4',
 'AQP4',
 'ASIC4',
 'B4GALNT3',
 'BARX2',
 'BCL11B',
 'BDNF',
 'BLNK',
 'BMPR1B',
 'C1QL3',
 'CACNG5',
 'CALB2',
 'CAMK2D',
 'CAR3',
 'CBLN2',
 'CBLN4',
 'CCBE1',
 'CCDC3',
 'CD14',
 'CD24A',
 'CDCP1',
 'CDH12',
 'CDH13',
 'CDH20',
 'CDH9',
 'CEACAM9',
 'CEMIP',
 'CHN2',
 'CHRM2',
 'CLDN5',
 'CNTNAP5B',
 'COBLL1',
 'COL15A1',
 'COL23A1',
 'COL24A1',
 'COL25A1',
 'CPLX3',
 'CRISPLD2',
 'CSPG4',
 'CTSS',
 'CUX2',
 'CXCL14',
 'DAAM2',
 'DNASE1L3',
 'DSCAML1',
 'EGFEM1',
 'EGFR',
 'ELFN1',
 'EPHA7',
 'FAM19A2',
 'FAM84B',
 'FBXL7',
 'FEZF2',
 'FLRT3',
 'FLT1',
 'FOSB',
 'FREM2',
 'FST',
 'GFAP',
 'GPC6',
 'GRIK1',
 'GRIN3A',
 'GRM1',
 'GRM8',
 'HS3ST5',
 'IGF2',
 'IGFBP5',
 'IKZF2',
 'INPP4B',
 'IQGAP2',
 'ITGB8',
 'KCNG1',
 'L3MBTL4',
 'LAMA3',
 'LHX6',
 'LMO1',
 'LSP1',
 'LUZP2',
 'LYPD1',
 'MARCH1',
 'MARCKSL1',
 'MEIS2',
 'MRC1',
 'MYH14',
 'NDST4',
 'NKAIN3',
 'NNMT',
 'NOS1',
 'NPNT',
 'NR2F2',
 'NR4A1',
 'NR4A2',
 'NTNG2',
 'NXPH1',
 'NXPH4',
 'OLAH',
 'OLFM3',
 'OPRK1',
 'OSR1',
 'OTOF',
 'PARM1',
 'PCDH8',
 'PDE11A',
 'PDGFC',
 'PDGFRA',
 'PDLIM5',
 'PHACTR2',
 'PLCH1',
 'PLCXD3',
 'PLD5',
 'PLEKHG3',
 'POU3F1',
 'POU3F3',
 'POU6F2',
 'PRDM8',
 'PROX1',
 'PRR16',
 'PRSS12',
 'PTGER3',
 'PTPRK',
 'PTPRM',
 'PTPRT',
 'PTPRU',
 'PXDC1',
 'RAMP1',
 'RELN',
 'RFX3',
 'RGS5',
 'RGS6',
 'RNF152',
 'ROR1',
 'RORB',
 'RXFP1',
 'RXFP2',
 'SATB2',
 'SCGN',
 'SEMA5A',
 'SERTM1',
 'SGCD',
 'SHISA9',
 'SLC17A6',
 'SLC17A8',
 'SLC25A13',
 'SLC30A3',
 'SLC32A1',
 'SLC44A5',
 'SLCO5A1',
 'SOX10',
 'SOX6',
 'SPON1',
 'ST6GALNAC5',
 'SULF1',
 'SULF2',
 'SYNDIG1',
 'SYT10',
 'SYT6',
 'TBC1D4',
 'TCAP',
 'TENM3',
 'THBS2',
 'THSD7A',
 'TIMP3',
 'TMEM163',
 'TMTC2',
 'TOX',
 'TRP53I11',
 'TRPC4',
 'TRPC6',
 'TSHZ2',
 'TUNAR',
 'UBASH3B',
 'UNC13C',
 'UNC5B',
 'UNC5D',
 'UST',
 'VIPR2',
 'VTN',
 'VWC2',
 'WIPF3',
 'WNT7B',
 'ZFP804B',
 'BLANK-2',
 'BLANK-4',
 '1810046K07RIK',
 'ADAMTS2',
 'ADAMTS4',
 'ADRA1B',
 'ALK',
 'BGN',
 'BRINP3',
 'CCDC162',
 'CDCA7',
 'CHAT',
 'CHRNA2',
 'COL14A1',
 'CORIN',
 'CRHR2',
 'EGLN3',
 'EGR2',
 'ENPP6',
 'FOXP2',
 'GLRA1',
 'IGFBP4',
 'IL4RA',
 'KCNJ8',
 'LTF',
 'MOXD1',
 'MRGPRX2',
 'NHS',
 'NPSR1',
 'PRSS23',
 'RSPO1',
 'SEMA3E',
 'SNCG',
 'TNFAIP6',
 'BLANK-6',
 'BLANK-10',
 '5730522E02RIK',
 'CCDC80',
 'DMKN',
 'HPSE',
 'IL1RAPL2',
 'LYZL4',
 'MUC20',
 'NPAS1',
 'TH',
 'BLANK-3',
 'BLANK-8',
 'BLANK-9',
 'CHODL',
 'CLRN1',
 'NXPH2',
 'PROKR2',
 'RERG',
 'BLANK-1',
 'BLANK-7',
 'B4GALNT2',
 'CCNB1',
 'NPY2R',
 'PROK2',
 'SERPINF1',
 'SP8',
 'TEDDM3',
 'C1QTNF7',
 '1700022I11RIK',
 'FNDC7',
 'OPALIN',
 '5031425F14RIK',
 'BLANK-5']

In [30]:
matches = reflat[reflat['hg38.kgXref.geneSymbol'].isin(genes)]
matches.shape

(1785, 4)

In [12]:
len(genes)

252

In [13]:
matches

,#hg38.knownGene.name,hg38.kgXref.geneSymbol,hg38.kgXref.refseq,hg38.kgXref.description
3770,ENST00000345512.7,PTPRU,NM_005704,Homo sapiens protein tyrosine phosphatase rece...
3771,ENST00000373779.8,PTPRU,NM_133178,Homo sapiens protein tyrosine phosphatase rece...
3772,ENST00000428026.6,PTPRU,NM_001195001,Homo sapiens protein tyrosine phosphatase rece...
3773,ENST00000460170.2,PTPRU,NM_133177,Homo sapiens protein tyrosine phosphatase rece...
3774,ENST00000527027.1,PTPRU,NaN,"protein tyrosine phosphatase, receptor type U ..."
...,...,...,...,...
242803,ENST00000634226.1,CALB2,NaN,calbindin 2 (from HGNC CALB2)
243645,ENST00000633761.1,SERPINF1,NaN,serpin family F member 1 (from HGNC SERPINF1)
243646,ENST00000632258.1,SERPINF1,NaN,serpin family F member 1 (from HGNC SERPINF1)
243647,ENST00000632001.1,SERPINF1,NaN,serpin family F member 1 (from HGNC SERPINF1)
243648,ENST00000632188.1,SERPINF1,NaN,serpin family F member 1 (from HGNC SERPINF1)

In [42]:
252-226

26

In [31]:
matches['hg38.kgXref.geneSymbol'].unique().size

226

In [32]:
ensg_symbol = pd.read_csv('../processed_data/ENSG_symbol.txt')
ensg_symbol.head()

              ENSG       symbol
0  ENSG00000223972      DDX11L1
1  ENSG00000227232       WASH7P
2  ENSG00000278267    MIR6859-1
3  ENSG00000243485  MIR1302-2HG
4  ENSG00000284332    MIR1302-2

In [33]:
matches = matches.drop_duplicates('hg38.kgXref.geneSymbol')
matches.head()

,#hg38.knownGene.name,hg38.kgXref.geneSymbol,hg38.kgXref.refseq,hg38.kgXref.description
3770,ENST00000345512.7,PTPRU,NM_005704,Homo sapiens protein tyrosine phosphatase rece...
4112,ENST00000329421.8,MARCKSL1,NM_023009,"Homo sapiens MARCKS like 1 (MARCKSL1), transcr..."
4652,ENST00000612451.4,RSPO1,NM_001242910,"Homo sapiens R-spondin 1 (RSPO1), transcript v..."
4733,ENST00000373012.5,POU3F1,NM_002699,"Homo sapiens POU class 3 homeobox 1 (POU3F1), ..."
7477,ENST00000371079.6,ROR1,NM_005012,Homo sapiens receptor tyrosine kinase like orp...

In [34]:
matches = matches.merge(
    ensg_symbol,
    left_on='hg38.kgXref.geneSymbol',
    right_on='symbol',
    how='inner',
)

matches

,#hg38.knownGene.name,hg38.kgXref.geneSymbol,hg38.kgXref.refseq,hg38.kgXref.description,ENSG,symbol
0,ENST00000345512.7,PTPRU,NM_005704,Homo sapiens protein tyrosine phosphatase rece...,ENSG00000060656,PTPRU
1,ENST00000329421.8,MARCKSL1,NM_023009,"Homo sapiens MARCKS like 1 (MARCKSL1), transcr...",ENSG00000175130,MARCKSL1
2,ENST00000612451.4,RSPO1,NM_001242910,"Homo sapiens R-spondin 1 (RSPO1), transcript v...",ENSG00000169218,RSPO1
3,ENST00000373012.5,POU3F1,NM_002699,"Homo sapiens POU class 3 homeobox 1 (POU3F1), ...",ENSG00000185668,POU3F1
4,ENST00000371079.6,ROR1,NM_005012,Homo sapiens receptor tyrosine kinase like orp...,ENSG00000185483,ROR1
...,...,...,...,...,...,...
222,ENST00000327783.8,GRIK1,NM_001330994,Homo sapiens glutamate ionotropic receptor kai...,ENSG00000171189,GRIK1
223,ENST00000406028.1,CLDN5,NaN,claudin 5 (from HGNC CLDN5),ENSG00000184113,CLDN5
224,ENST00000266085.6,TIMP3,NM_000362,Homo sapiens TIMP metallopeptidase inhibitor 3...,ENSG00000100234,TIMP3
225,ENST00000651746.1,SOX10,NaN,SRY-box 10 (from HGNC SOX10),ENSG00000100146,SOX10
226,ENST00000339464.9,WNT7B,NM_058238,"Homo sapiens Wnt family member 7B (WNT7B), mRN...",ENSG00000188064,WNT7B

In [35]:
matches.drop(columns=['#hg38.knownGene.name','hg38.kgXref.geneSymbol'],inplace=True)

In [36]:
matches.rename(columns={'hg38.kgXref.description':'description','hg38.kgXref.refseq':'refseq'},inplace=True)

In [45]:
matches[['symbol','ENSG','description','refseq']]

,symbol,ENSG,description,refseq
0,PTPRU,ENSG00000060656,Homo sapiens protein tyrosine phosphatase rece...,NM_005704
1,MARCKSL1,ENSG00000175130,"Homo sapiens MARCKS like 1 (MARCKSL1), transcr...",NM_023009
2,RSPO1,ENSG00000169218,"Homo sapiens R-spondin 1 (RSPO1), transcript v...",NM_001242910
3,POU3F1,ENSG00000185668,"Homo sapiens POU class 3 homeobox 1 (POU3F1), ...",NM_002699
4,ROR1,ENSG00000185483,Homo sapiens receptor tyrosine kinase like orp...,NM_005012
...,...,...,...,...
222,GRIK1,ENSG00000171189,Homo sapiens glutamate ionotropic receptor kai...,NM_001330994
223,CLDN5,ENSG00000184113,claudin 5 (from HGNC CLDN5),NaN
224,TIMP3,ENSG00000100234,Homo sapiens TIMP metallopeptidase inhibitor 3...,NM_000362
225,SOX10,ENSG00000100146,SRY-box 10 (from HGNC SOX10),NaN
226,WNT7B,ENSG00000188064,"Homo sapiens Wnt family member 7B (WNT7B), mRN...",NM_058238

In [37]:
matches[['symbol','ENSG','description','refseq']].to_csv('../processed_data/gene_info.csv',index=False)

In [43]:
i = 0
for p in np.setdiff1d(genes,matches['symbol']):
    i += 1
    print(p)

1700022I11RIK
1810046K07RIK
5031425F14RIK
5730522E02RIK
BLANK-1
BLANK-10
BLANK-2
BLANK-3
BLANK-4
BLANK-5
BLANK-6
BLANK-7
BLANK-8
BLANK-9
CAR3
CCDC162
CD24A
CEACAM9
CNTNAP5B
EGFEM1
FAM19A2
FAM84B
IL4RA
MARCH1
TEDDM3
TRP53I11
ZFP804B

In [44]:
i

27